// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWallet.Api.Infrastructure.Persistence;

#nullable disable

namespace NovaWallet.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LedgerDbContext))]
    [Migration("20260916151209_AuditProtection")]
    partial class AuditProtection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("NovaWallet.Api.Domain.AuditEntry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<Guid>("ActorSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfterKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceBeforeKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Operation")
                        .HasColumnType("int");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TraceId")
                        .IsRequired()
                        .HasColumnType("varchar(32)");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WalletId", "OperationId")
                        .IsUnique();

                    b.HasIndex("WalletId", "OccurredAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("AuditEntries", null, t =>
                        {
                            t.HasCheckConstraint("CK_Audit_Amounts", "AmountKobo > 0 AND BalanceBeforeKobo >= 0 AND BalanceAfterKobo >= 0");

                            t.HasCheckConstraint("CK_Audit_Arithmetic", "(Operation = 2 AND BalanceBeforeKobo >= AmountKobo AND BalanceAfterKobo = BalanceBeforeKobo - AmountKobo) OR (Operation IN (1,3) AND BalanceAfterKobo >= AmountKobo AND BalanceBeforeKobo = BalanceAfterKobo - AmountKobo)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("varchar(128)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<Guid?>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RequestHash")
                        .IsRequired()
                        .HasColumnType("binary(32)");

                    b.Property<string>("ResponseContentType")
                        .HasColumnType("varchar(64)");

                    b.Property<string>("ResponseJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseLocation")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .UseCollation("Latin1_General_100_BIN2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_Idempotency_Outcome", "(Status = 1 AND HttpStatusCode IS NULL AND CompletedAtUtc IS NULL AND OperationId IS NULL AND ResponseJson IS NULL) OR (Status IN (2,3) AND HttpStatusCode IS NOT NULL AND ResponseJson IS NOT NULL AND ResponseContentType IS NOT NULL AND CompletedAtUtc IS NOT NULL AND ((Status = 2 AND OperationId IS NOT NULL AND HttpStatusCode = 200) OR (Status = 3 AND OperationId IS NULL AND HttpStatusCode = 422)))");
                        });
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.Transfer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CompletedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("DestinationWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InitiatedBySubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceWalletId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DestinationWalletId");

                    b.HasIndex("SourceWalletId", "CompletedAtUtc");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("SourceWalletId", "CompletedAtUtc"), new[] { "AmountKobo", "Status" });

                    b.ToTable("Transfers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Transfer_Amount", "AmountKobo > 0");

                            t.HasCheckConstraint("CK_Transfer_Status", "Status = 1");

                            t.HasCheckConstraint("CK_Transfer_Wallets", "SourceWalletId <> DestinationWalletId");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("BalanceKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("char(3)");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .IsUnique();

                    b.ToTable("Wallets", null, t =>
                        {
                            t.HasCheckConstraint("CK_Wallet_Balance", "BalanceKobo >= 0");

                            t.HasCheckConstraint("CK_Wallet_Currency", "Currency = 'NGN'");
                        });
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.WalletTransaction", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AmountKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceAfterKobo")
                        .HasColumnType("bigint");

                    b.Property<long>("BalanceBeforeKobo")
                        .HasColumnType("bigint");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TransferId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TransferId");

                    b.HasIndex("WalletId", "OperationId")
                        .IsUnique();

                    b.HasIndex("WalletId", "CreatedAtUtc", "Id")
                        .IsDescending(false, true, true);

                    b.ToTable("WalletTransactions", null, t =>
                        {
                            t.HasCheckConstraint("CK_History_Amounts", "AmountKobo > 0 AND BalanceBeforeKobo >= 0 AND BalanceAfterKobo >= 0");

                            t.HasCheckConstraint("CK_History_Arithmetic", "(Type = 2 AND BalanceBeforeKobo >= AmountKobo AND BalanceAfterKobo = BalanceBeforeKobo - AmountKobo) OR (Type IN (1,3) AND BalanceAfterKobo >= AmountKobo AND BalanceBeforeKobo = BalanceAfterKobo - AmountKobo)");

                            t.HasCheckConstraint("CK_History_Reference", "(Type = 1 AND TransferId IS NULL) OR (Type IN (2,3) AND TransferId IS NOT NULL AND TransferId = OperationId)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.AuditEntry", b =>
                {
                    b.HasOne("NovaWallet.Api.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.Transfer", b =>
                {
                    b.HasOne("NovaWallet.Api.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NovaWallet.Api.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NovaWallet.Api.Domain.WalletTransaction", b =>
                {
                    b.HasOne("NovaWallet.Api.Domain.Transfer", null)
                        .WithMany()
                        .HasForeignKey("TransferId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NovaWallet.Api.Domain.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
